import { defineConfig, type Plugin } from "vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { nitro } from "nitro/vite";
import tailwindcss from "@tailwindcss/vite";
import tsConfigPaths from "vite-tsconfig-paths";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { copyFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { pwaManifest } from "./pwa-config.mjs";

/**
 * Vite emits the MapLibre worker file as a hashed asset, but the worker itself
 * imports `./maplibre-gl-shared.mjs` at runtime. Vite doesn't follow that
 * dynamic import, so the shared module can be missing in the output and the
 * GeoJSON route layer never renders. This plugin copies the shared module next
 * to the worker using the exact file name the worker expects.
 */
function maplibreWorkerShared(): Plugin {
  return {
    name: "maplibre-worker-shared",
    writeBundle(options) {
      const outDir = options.dir || "dist/client";
      const src = resolve("node_modules/maplibre-gl/dist/maplibre-gl-shared.mjs");
      const dest = resolve(outDir, "assets/maplibre-gl-shared.mjs");
      mkdirSync(dirname(dest), { recursive: true });
      copyFileSync(src, dest);
    },
  };
}

export default defineConfig(({ command, mode }) => ({
  resolve: {
    alias: { "@": resolve(process.cwd(), "src") },
    // Keep a single copy of React and TanStack Query in the bundle — several
    // packages here (radix-ui, tanstack-router) depend on them, and a
    // duplicate copy silently breaks context/hooks.
    dedupe: [
      "react",
      "react-dom",
      "react/jsx-runtime",
      "react/jsx-dev-runtime",
      "@tanstack/react-query",
      "@tanstack/query-core",
    ],
  },

  optimizeDeps: {
    include: [
      "react",
      "react-dom",
      "react-dom/client",
      "react/jsx-runtime",
      "react/jsx-dev-runtime",
    ],
    // maplibre-gl ships a web worker the dep optimizer can't pre-bundle.
    exclude: ["maplibre-gl"],
  },

  server: {
    host: "::",
    port: 8080,
  },

  plugins: [
    tailwindcss(),
    tsConfigPaths({ projects: ["./tsconfig.json"] }),
    tanstackStart({
      // Redirect TanStack Start's bundled server entry to src/server.ts (our
      // SSR error wrapper). nitro/vite builds from this.
      server: { entry: "server" },
      // Fail the build if server-only code (anything under **/server/**, or
      // anything importing the "server-only" package) ends up in a client
      // bundle, instead of silently shipping it.
      importProtection: {
        behavior: "error",
        client: { files: ["**/server/**"], specifiers: ["server-only"] },
      },
    }),
    // Nitro only needs to run for the actual production build — the Vite
    // dev server serves routes directly. `--mode node` (see the "build:node"
    // script) switches the output to a plain Node server for self-hosting
    // (Docker, Unraid, etc.) instead of a Cloudflare Worker bundle — see
    // the Dockerfile and the "Self-hosting with Docker" section in README.md.
    command === "build"
      ? nitro({ defaultPreset: mode === "node" ? "node-server" : "cloudflare-module" })
      : null,
    react(),
    maplibreWorkerShared(),
    // IMPORTANT: this only generates manifest.webmanifest at build time (it
    // correctly lands in the real static output, `.output/public`, because
    // Nitro handles that file specially). It does NOT generate the actual
    // service worker for production. `outDir`/`strategies: "generateSW"`
    // below make VitePWA write a `sw.js` into `dist/client`, but for this
    // TanStack Start + Nitro (cloudflare-module) setup, `dist/client` is a
    // vestigial build pass — the real app bundle Nitro serves lives in
    // `.output/public`, and Vite's build lifecycle doesn't give this plugin
    // a reliable hook into that directory once Nitro has finished assembling
    // it. Registering the sw.js this plugin emits would 404 in production.
    // The real, production service worker is generated by
    // `scripts/generate-sw.mjs` (run as part of `npm run build`), using
    // `workbox-build` directly against the finished `.output/public`
    // directory. Both share `pwa-config.mjs` as the single source of truth
    // for the manifest and caching rules.
    VitePWA({
      strategies: "generateSW",
      registerType: "autoUpdate",
      filename: "sw.js",
      outDir: "dist/client",
      // The guarded wrapper in src/lib/pwa.ts is the only registrar, and it
      // only ever registers "/sw.js" — the one scripts/generate-sw.mjs makes.
      injectRegister: null,
      devOptions: { enabled: false },
      manifest: pwaManifest,
    }),
  ],
}));
