/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiDeleteAccountRouteImport } from './routes/api/delete-account'
import { Route as RidesIndexRouteImport } from './routes/rides.index'
import { Route as RidesIdIndexRouteImport } from './routes/rides.$id.index'
import { Route as RidesIdNavRouteImport } from './routes/rides.$id.nav'
import { Route as ApiCloudNextcloudConnectRouteImport } from './routes/api/cloud/nextcloud/connect'
import { Route as ApiCloudNextcloudDisconnectRouteImport } from './routes/api/cloud/nextcloud/disconnect'
import { Route as ApiCloudNextcloudStatusRouteImport } from './routes/api/cloud/nextcloud/status'
import { Route as ApiCloudNextcloudSyncRouteImport } from './routes/api/cloud/nextcloud/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDeleteAccountRoute = ApiDeleteAccountRouteImport.update({
  id: '/api/delete-account',
  path: '/api/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIndexRoute = RidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIdIndexRoute = RidesIdIndexRouteImport.update({
  id: '/rides/$id/',
  path: '/rides/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIdNavRoute = RidesIdNavRouteImport.update({
  id: '/rides/$id/nav',
  path: '/rides/$id/nav',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudNextcloudConnectRoute =
  ApiCloudNextcloudConnectRouteImport.update({
    id: '/api/cloud/nextcloud/connect',
    path: '/api/cloud/nextcloud/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCloudNextcloudDisconnectRoute =
  ApiCloudNextcloudDisconnectRouteImport.update({
    id: '/api/cloud/nextcloud/disconnect',
    path: '/api/cloud/nextcloud/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCloudNextcloudStatusRoute = ApiCloudNextcloudStatusRouteImport.update({
  id: '/api/cloud/nextcloud/status',
  path: '/api/cloud/nextcloud/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudNextcloudSyncRoute = ApiCloudNextcloudSyncRouteImport.update({
  id: '/api/cloud/nextcloud/sync',
  path: '/api/cloud/nextcloud/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/rides/': typeof RidesIndexRoute
  '/rides/$id/nav': typeof RidesIdNavRoute
  '/rides/$id/': typeof RidesIdIndexRoute
  '/api/cloud/nextcloud/connect': typeof ApiCloudNextcloudConnectRoute
  '/api/cloud/nextcloud/disconnect': typeof ApiCloudNextcloudDisconnectRoute
  '/api/cloud/nextcloud/status': typeof ApiCloudNextcloudStatusRoute
  '/api/cloud/nextcloud/sync': typeof ApiCloudNextcloudSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/rides': typeof RidesIndexRoute
  '/rides/$id/nav': typeof RidesIdNavRoute
  '/rides/$id': typeof RidesIdIndexRoute
  '/api/cloud/nextcloud/connect': typeof ApiCloudNextcloudConnectRoute
  '/api/cloud/nextcloud/disconnect': typeof ApiCloudNextcloudDisconnectRoute
  '/api/cloud/nextcloud/status': typeof ApiCloudNextcloudStatusRoute
  '/api/cloud/nextcloud/sync': typeof ApiCloudNextcloudSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/rides/': typeof RidesIndexRoute
  '/rides/$id/nav': typeof RidesIdNavRoute
  '/rides/$id/': typeof RidesIdIndexRoute
  '/api/cloud/nextcloud/connect': typeof ApiCloudNextcloudConnectRoute
  '/api/cloud/nextcloud/disconnect': typeof ApiCloudNextcloudDisconnectRoute
  '/api/cloud/nextcloud/status': typeof ApiCloudNextcloudStatusRoute
  '/api/cloud/nextcloud/sync': typeof ApiCloudNextcloudSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/oauth-callback'
    | '/reset-password'
    | '/settings'
    | '/api/delete-account'
    | '/rides/'
    | '/rides/$id/nav'
    | '/rides/$id/'
    | '/api/cloud/nextcloud/connect'
    | '/api/cloud/nextcloud/disconnect'
    | '/api/cloud/nextcloud/status'
    | '/api/cloud/nextcloud/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/oauth-callback'
    | '/reset-password'
    | '/settings'
    | '/api/delete-account'
    | '/rides'
    | '/rides/$id/nav'
    | '/rides/$id'
    | '/api/cloud/nextcloud/connect'
    | '/api/cloud/nextcloud/disconnect'
    | '/api/cloud/nextcloud/status'
    | '/api/cloud/nextcloud/sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/explore'
    | '/oauth-callback'
    | '/reset-password'
    | '/_authenticated/settings'
    | '/api/delete-account'
    | '/rides/'
    | '/rides/$id/nav'
    | '/rides/$id/'
    | '/api/cloud/nextcloud/connect'
    | '/api/cloud/nextcloud/disconnect'
    | '/api/cloud/nextcloud/status'
    | '/api/cloud/nextcloud/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiDeleteAccountRoute: typeof ApiDeleteAccountRoute
  RidesIndexRoute: typeof RidesIndexRoute
  RidesIdNavRoute: typeof RidesIdNavRoute
  RidesIdIndexRoute: typeof RidesIdIndexRoute
  ApiCloudNextcloudConnectRoute: typeof ApiCloudNextcloudConnectRoute
  ApiCloudNextcloudDisconnectRoute: typeof ApiCloudNextcloudDisconnectRoute
  ApiCloudNextcloudStatusRoute: typeof ApiCloudNextcloudStatusRoute
  ApiCloudNextcloudSyncRoute: typeof ApiCloudNextcloudSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/delete-account': {
      id: '/api/delete-account'
      path: '/api/delete-account'
      fullPath: '/api/delete-account'
      preLoaderRoute: typeof ApiDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/': {
      id: '/rides/'
      path: '/rides'
      fullPath: '/rides/'
      preLoaderRoute: typeof RidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$id/': {
      id: '/rides/$id/'
      path: '/rides/$id'
      fullPath: '/rides/$id/'
      preLoaderRoute: typeof RidesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$id/nav': {
      id: '/rides/$id/nav'
      path: '/rides/$id/nav'
      fullPath: '/rides/$id/nav'
      preLoaderRoute: typeof RidesIdNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloud/nextcloud/connect': {
      id: '/api/cloud/nextcloud/connect'
      path: '/api/cloud/nextcloud/connect'
      fullPath: '/api/cloud/nextcloud/connect'
      preLoaderRoute: typeof ApiCloudNextcloudConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloud/nextcloud/disconnect': {
      id: '/api/cloud/nextcloud/disconnect'
      path: '/api/cloud/nextcloud/disconnect'
      fullPath: '/api/cloud/nextcloud/disconnect'
      preLoaderRoute: typeof ApiCloudNextcloudDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloud/nextcloud/status': {
      id: '/api/cloud/nextcloud/status'
      path: '/api/cloud/nextcloud/status'
      fullPath: '/api/cloud/nextcloud/status'
      preLoaderRoute: typeof ApiCloudNextcloudStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloud/nextcloud/sync': {
      id: '/api/cloud/nextcloud/sync'
      path: '/api/cloud/nextcloud/sync'
      fullPath: '/api/cloud/nextcloud/sync'
      preLoaderRoute: typeof ApiCloudNextcloudSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiDeleteAccountRoute: ApiDeleteAccountRoute,
  RidesIndexRoute: RidesIndexRoute,
  RidesIdNavRoute: RidesIdNavRoute,
  RidesIdIndexRoute: RidesIdIndexRoute,
  ApiCloudNextcloudConnectRoute: ApiCloudNextcloudConnectRoute,
  ApiCloudNextcloudDisconnectRoute: ApiCloudNextcloudDisconnectRoute,
  ApiCloudNextcloudStatusRoute: ApiCloudNextcloudStatusRoute,
  ApiCloudNextcloudSyncRoute: ApiCloudNextcloudSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
